# Site settings
title: Julian’s Cybersecurity Portfolio
email: j [at] juliandelorenzo.com
description: > # this means to ignore newlines until "baseurl:"
  A portfolio website for Julian de Lorenzo’s cybersecurity and programming projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "julian-del.github.io" # the base hostname & protocol for your site
  # twitter_username: 
github_username:  julian-del

# Build settings
markdown: kramdown
permalink: pretty

  # defaults:
  #  - scope:
    #    path: "assets/img"
